<option value=""  <% if("".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>></option>
<option value="01" <% if("01".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>01</option>
<option value="02" <% if("02".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>02</option>
<option value="03" <% if("03".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>03</option>
<option value="04" <% if("04".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>04</option>
<option value="05" <% if("05".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>05</option>
<option value="06" <% if("06".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>06</option>
<option value="07" <% if("07".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>07</option>
<option value="08" <% if("08".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>08</option>
<option value="09" <% if("09".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>09</option>
<option value="10" <% if("10".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>10</option>
<option value="11" <% if("11".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>11</option>
<option value="12" <% if("12".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>12</option>
<option value="13" <% if("13".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>13</option>
<option value="14" <% if("14".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>14</option>
<option value="15" <% if("15".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>15</option>
<option value="16" <% if("16".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>16</option>
<option value="17" <% if("17".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>17</option>
<option value="18" <% if("18".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>18</option>
<option value="19" <% if("19".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>19</option>
<option value="20" <% if("20".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>20</option>
<option value="21" <% if("21".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>21</option>
<option value="22" <% if("22".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>22</option>
<option value="23" <% if("23".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>23</option>
<option value="24" <% if("24".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>24</option>
<option value="25" <% if("25".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>25</option>
<option value="26" <% if("26".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>26</option>
<option value="27" <% if("27".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>27</option>
<option value="28" <% if("28".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>28</option>
<option value="29" <% if("29".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>29</option>
<option value="30" <% if("30".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>30</option>
<option value="31" <% if("31".equals(session.getAttribute("dayS"))) { out.print("selected=\"selected\""); } %>>31</option>